In [1]:
from alpha_vantage.timeseries import TimeSeries
import pandas as pd
from sklearn import preprocessing
import numpy as np

def save_data(symbol):
    API_KEY = 'DTJYUMAWMLMQYLRB'

    ts = TimeSeries(key=API_KEY, output_format='pandas')
    # Get json object with the intraday data and another with  the call's metadata
    data, meta_data = ts.get_daily(symbol, outputsize='full')
    data.to_csv(f'./{symbol}_daily.csv')

def load_data(symbol):
    history_points = 50
    data = pd.read_csv(f'./{symbol}_daily.csv')
    data = data.drop('date', axis=1)
    data = data.drop(0, axis=0)
    return data
#     data_normaliser = preprocessing.MinMaxScaler()
#     data_normalised = data_normaliser.fit_transform(data)
#        # using the last {history_points} open high low close volume data points, predict the next open value
    
#     return data_normalised

In [5]:
data = load_data('MSFT')
data

       1. open   2. high  3. low  4. close   5. volume
1     140.0000  147.4998  135.00    146.57  80354185.0
2     140.0000  149.3500  135.00    135.42  87905868.0
3     147.5000  161.9100  140.73    158.83  92727446.0
4     145.3000  153.4700  138.58    139.06  93226366.0
5     157.1304  157.7000  151.15    153.63  56504304.0
...        ...       ...     ...       ...         ...
5028  102.8100  105.6200  101.12    103.25  46987900.0
5029   96.7500  103.1200   96.50    102.75  40824400.0
5030   98.7500   99.7500   96.50     97.37  23886500.0
5031   95.2500   99.5000   94.50     99.37  40580800.0
5032   95.9400   96.6900   93.25     95.37  38650400.0

[5032 rows x 5 columns]

In [3]:
save_data('MSFT')

In [4]:
data = load_data('MSFT')
history_points = 50
data_normaliser = preprocessing.MinMaxScaler()
data_normalised = data_normaliser.fit_transform(data)
ohlcv_histories_normalised =      np.array([data_normalised[i  : i + history_points].copy() for i in range(len(data_normalised) - history_points)])
next_day_open_values_normalised = np.array([data_normalised[:,0][i + history_points].copy() for i in range(len(data_normalised) - history_points)])
next_day_open_values_normalised = np.expand_dims(next_day_open_values_normalised, -1)
next_day_open_values_normalised
next_day_open_values = np.expand_dims(next_day_open_values_normalised, -1)

In [121]:
next_day_open_values = np.array([data[:,0][i + history_points].copy() for i in range(len(data) - history_points)])

TypeError: '(slice(None, None, None), 0)' is an invalid key

In [122]:
data

       1. open  2. high    3. low  4. close   5. volume
1     162.8235  163.220  161.1800    161.34  20733946.0
2     161.8350  162.215  161.0300    162.09  21399951.0
3     158.9300  160.800  157.9491    160.09  27762026.0
4     159.3200  159.670  157.3200    157.58  21881740.0
5     157.0800  159.100  156.5100    159.03  20826702.0
...        ...      ...       ...       ...         ...
5027  110.5000  111.500  106.0000    107.00  48784100.0
5028  111.8100  116.500  111.7500    115.31  40741800.0
5029  107.1900  113.940  105.7500    112.25  36708200.0
5030  104.3700  108.620  101.5000    107.81  41572000.0
5031  108.5000  108.870  104.4400    105.81  33266200.0

[5031 rows x 5 columns]

In [123]:
data[:,0][50]

SyntaxError: unexpected EOF while parsing (<ipython-input-123-607f1aa0c1f3>, line 1)